name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted
    env:
      ASPNETCORE_ENVIRONMENT: Production
      # the port here should match the port in appsettings.json
      PORT: 6000

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Copy App Settings 
      # first lets copy the appsettings for the application
      run: cp ../../../appsettings.Production.json MacintoshBot
    - name: Publish
      # publish for linux-x64 architectures
      run: dotnet publish -r linux-x64
    - name: Kill existing process
      # kill the existing process (assume its on port 6000)
      run: lsof -t -i:$PORT | xargs kill
      continue-on-error: true
    - name: Deploy
      # run the application in the background
      # RUNNER_TRACKING_ID is used so the process does not get killed when the build script is finished
      run: |
        cd MacintoshBot/bin/Debug/net5.0/linux-x64/publish/
        RUNNER_TRACKING_ID="" && nohup dotnet exec MacintoshBot.dll &
