name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Copy App Settings 
      # first lets copy the appsettings for the application
      run: cp ~/github-actions/MacintoshBot/appsettings.Production.json /home/adam/github-actions/MacintoshBot/repo/MacintoshBot/MacintoshBot/MacintoshBot
    - name: Publish
      # publish for linux-x64 architectures
      run: dotnet publish -r linux-x64
    - name: Deploy
      # kill the existing process (assume its on port 6000)
      # run the application in the background
      run: kill $(lsof -t -i:6000)
      run: nohup dotnet exec /home/adam/github-actions/MacintoshBot/repo/MacintoshBot/MacintoshBot/MacintoshBot/bin/Debug/net5.0/linux-x64/publish/MacintoshBot.dll &
        
      
