name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Copy App Settings 
      # first lets copy the appsettings for the application
      run: cp ~/github-actions/MacintoshBot/appsettings.Production.json /home/adam/github-actions/MacintoshBot/repo/MacintoshBot/MacintoshBot/MacintoshBot
    - name: Publish
      # publish for linux-x64 architectures
      run: dotnet publish -r linux-x64
      
